version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5001:5001"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    volumes:
      - ./:/app
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_HOST: redis
    depends_on:
      - redis
    volumes:
      - ./:/app
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
